//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XMLAuthenticationProviderData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XMLAuthenticationProviderData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTest.XMLAuthenticationProviderData", typeof(XMLAuthenticationProviderData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;users&gt;
        ///	&lt;user prefix=&quot;mslot1!~mslot1@56344eba.rev.stofanet.dk&quot; network=&quot;network&quot; allow=&quot;false&quot;&gt;
        ///		&lt;commands&gt;
        ///			&lt;command name=&quot;commandName1&quot; right=&quot;read&quot;/&gt;
        ///			&lt;command name=&quot;commandName2&quot; right=&quot;write&quot;/&gt;
        ///		&lt;/commands&gt;
        ///	&lt;/user&gt;
        ///	&lt;user prefix=&quot;mslot2!~mslot2@56344eba.rev.stofanet.dk&quot; network=&quot;network&quot; allow=&quot;true&quot;&gt;
        ///		&lt;commands&gt;
        ///			&lt;command name=&quot;commandName1&quot; right=&quot;read|write|execute&quot;/&gt;
        ///			&lt;command name=&quot;commandName2&quot; right=&quot;read&quot;/&gt;
        ///		&lt;/commands&gt;
        ///	&lt;/user&gt;
        ///&lt;/users&gt;.
        /// </summary>
        internal static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
    }
}
